version: '3.8'

volumes:
  openvpn-data: # Dedicated volume for OpenVPN data
    driver: local

networks:
  openvpn-net: # Dedicated network for OpenVPN
    driver: bridge

services:
  openvpn-as:
    image: openvpn/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    ports:
      - "943:943"
      - "443:443"
      - "1194:1194/udp"
    volumes:
      - openvpn-data:/openvpn
    networks:
      - openvpn-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:943/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always # Ensures the container restarts regardless of the failure type
